name: Other
description: Use this issue for any questions/suggestions or closed internships.
title: "Issue: "
labels: ["other"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this issue!
  - type: dropdown
    id: category
    attributes:
      label: Select a category
      description: Please select the category that best fits your issue.
      multiple: false
      options:
        - 'Question'
        - 'Suggestion'
        - 'Closed Internship'
        - 'Other'
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Issue/Question/Closed Internship
      description: Please provide a brief description of the issue, question, closed internship, or suggestion.
      placeholder: ex. I have a question about the repo, I have a suggestion for the repo, An internship has been closed, How can I contribute to the repo?, etc.
    validations:
      required: true
